- section: "Mirrors"
  device: focusing_mirror
  type: PiezoMirror
  import_from: "dodal.devices.i10"
  params:
    prefix: 'f"{PREFIX.beamline_prefix}-OP-FOCS-01:"'

- section: "Mirrors"
  device: switching_mirror
  type: PiezoMirror
  import_from: "dodal.devices.i10"
  params:
    prefix: "f'{PREFIX.beamline_prefix}-OP-SWTCH-01:'"
  factory_args: {}
